version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Entered the install phase..."
      # upgrade pip
      - pip install pip==21.0.1
      - pip install yamlordereddictloader==0.4.0
  pre_build:
    commands:
      - echo "Entered the CodeBuild pre-build phase..."
      #Write Invocation Metric
      - aws cloudwatch put-metric-data --metric-name Invocations --namespace Pipeline --unit Count --value 1 --dimensions PipelineType=Build,Pipeline="${CODEBUILD_INITIATOR}"
  build:
    commands:
      - echo "Entered the CodeBuild build phase..."
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > integration/aws/commit_hash.txt
      - chmod +x ./integration/aws/scripts/token_replacer/build_environments.py
      - ./integration/aws/scripts/token_replacer/build_environments.py -f ./integration/aws/build.yml
  post_build:
    commands:
      - echo "Entered the CodeBuild post-build phase..."
      #Write Failure Metric if failing
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq "0" ]; then aws cloudwatch put-metric-data --metric-name Failures --namespace Pipeline --unit Count --value 1 --dimensions PipelineType=Build,Pipeline="${CODEBUILD_INITIATOR}"; fi
artifacts:
  files:
    - bin/**/* #Shell globbing, see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
    - integration/aws/**/*
